on:
  push:
    branches:
      - development
      - main
      - ci-*
  pull_request:
    branches-ignore:
      - "launchpad**" # TODO: Remove this filter once the branch is merged into development
    types:
      - opened
      - reopened
      - synchronize

name: CI

env:
  toolchain: nightly-2021-11-20
  CARGO_HTTP_MULTIPLEXING: false
  CARGO_TERM_COLOR: always
  PROTOC: protoc

jobs:
  check-nightly:
    uses:
      ./.github/workflows/reusable-ci-jobs.yml
    with:
      check-ffi: true
      toolchain: ${{ env.toolchain }}

  check-stable:
    uses:
      ./.github/workflows/reusable-ci-jobs.yml
    with:
      check-ffi: false
      toolchain: stable
      profile: "--release"

  check-js-apps:
    uses:
      ./.github/workflows/reusable-ci-jobs.yml
    with:
      lints: false
      build-tari: false
      toolchain: stable
      build-collectibles: true
      build-explorer: true

  licenses:
    uses:
      ./.github/workflows/reusable-licenses.yml

  tests:
    uses:
      ./.github/workflows/reusable-ci-tests.yml
    with:
      toolchain: ${{ env.toolchain }}
      profile: "--release"
      test-tari: true
      test-wasm: true

  # Allows other workflows to know the PR number
  artifacts:
    name: test
    runs-on: ubuntu-18.04
    steps:
      - name: Save the PR number in an artifact
        shell: bash
        env:
          PR_NUM: ${{ github.event.number }}
        run: echo $PR_NUM > pr_num.txt

      - name: Upload the PR number
        uses: actions/upload-artifact@v2
        with:
          name: pr_num
          path: ./pr_num.txt
