on:
  push:
    branches:
      - launchpad_such_wow
  pull_request:
    branches:
      - "launchpad**" # TODO: Remove this filter once the branch is merged into development
    types:
      - opened
      - reopened
      - synchronize

name: CI

env:
  toolchain: nightly-2021-11-20
  CARGO_HTTP_MULTIPLEXING: false
  CARGO_TERM_COLOR: always
  PROTOC: protoc

jobs:
  check-stable-debug:
    uses:
      ./.github/workflows/reusable-ci-jobs.yml
    with:
      lints: true
      build-tari: true
      build-launchpad-fe: true
      check-ffi: false
      toolchain: stable
      build-collectibles: false
      build-explorer: false

  licenses:
    uses:
      ./.github/workflows/reusable-licenses.yml
